# https://taskfile.dev

version: '3'

tasks:
  serve:
    cmds:
      - browser-sync start --no-open --config ./bs-config.js
  scss:
    cmds:
      - sass --watch ./scss:./src/assets/css
  script-nav:
    cmds:
      - bun build --minify --target=browser --watch --outdir=./src/assets/scripts/ ./scripts/nav/nav.ts
  default:
    deps: [scss, script-nav, serve]
