# https://taskfile.dev

version: '3'

tasks:
  serve:
    cmds:
      - browser-sync start --no-open --config ./bs-config.js
  scss:
    cmds:
      - sass --watch ./scss:./src/assets/css
  script-nav:
    cmds:
      - bun build --minify --target=browser --watch --outdir=./src/assets/scripts/ ./scripts/nav/nav.ts
  script-dots:
    cmds:
      - bun build --minify --target=browser --watch --outdir=./src/assets/scripts/ ./scripts/dots/dots.ts
  deploy:
    cmds:
      - cd src && bsdtar --no-acls --no-mac-metadata --no-xattrs --exclude Dockerfile --exclude-vcs --exclude '*.yml' --exclude README.md --exclude '*.sh' -cf - . | kubectl -n dynamic-sites exec -it deploy/dynamic-sites -- tar -C /sites/teonite.com -xf -
  default:
    deps: [scss, script-nav, script-dots, serve]
